# Welcome to Jekyll!
#
# yourself editing these this file very often, consider using Jekyll's data files
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# feature for the data you need to update frequently.
#
# 'jekyll serve'. If you change this file, please restart the server process.
# For technical reasons, this file is *NOT* reloaded automatically when you use

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Hands-On PCB Engineering
description: Hands-On PCB Engineering at UC Berkeley IEEE Student Branch
url: 'https://ieee.github.io' # the base hostname & protocol for your site, e.g. http://example.com
exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "vendor"]
# Heading settings
lecture:
  time: "WeTh 8-10PM"
  location:
      name: "Cory 125"
      link: ""
heading_links:
  - text: "Zoom"
    url: ""
  - text: "Playlist"
    url: ""
lecture_prefix: "csXXX-sp25-lec"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.10.0
# color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
aux_links:
  Dark Mode:
    - '#'
  Attendance Form:
    - 'https://docs.google.com/forms/d/e/1FAIpQLScAalTDiOehc1rykgy44OmppocaB6nfgMRY5QcHMMMgT0nX9g/viewform'
  Lab Checkoff:
    - 'https://docs.google.com/forms/d/e/1FAIpQLScIDQ0Dz-9NYkdRUyHRlNhmfam70qAeXpOj3JnvU2_YxmGiHQ/viewform'
  Ed:
    - 'https://edstem.org/us/courses/73279/'
  Berkeley IEEE:
    - 'https://ieee.berkeley.edu'
footer_content:

# Collections for website data
collections:
  staffers:
  modules:
  schedules:
  announcements:
# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: staffers
    values:
      layout: staffer
      subpath: '/assets/staff_photos/'
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: schedules
    values:
      layout: schedule
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

plugins:
  - jekyll-seo-tag

color_scheme: wider

callouts:
  warning:
    title: Warning
    color: yellow
  story: # CS 161 custom config for story
    title: Story
    color: blue
  example: # CS 161 custom config for proj2
    title: Example
    color: blue
  question: # CS 161 custom config for proj2
    title: Design Question
    color: green

# For copy button on code
enable_copy_code_button: true

# CS 188 custom config variable
# Set this to true at the start of semesters to show a warning on the homepage
under_construction: false

# Set this to true to show a warning telling people on the waitlist to check FAQs
waitlist_warning: false
# Set this to true if discussion times are uncertain (populates on calendar.md)

discussions_under_construction: false

# Set this to true to archive the semester
outdated: false